import './globals.css';
import { inter, sophiaCondensed } from './static-fonts/font';
import NavBar from './navbar/navbar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="my-2">
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
